[package]
name = "stock"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.15.4"
chrono = "0.4.43"
csv = "1.4.0"
glob = "0.3.3"
plotters = "0.3.7"
regex = "1.12.2"
rocket = { version = "0.5.1", features = ["json"] }
