services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: 1
      MARIADB_DATABASE: appdb
      MARIADB_USER: app
      MARIADB_PASSWORD: apppass
      TZ: Asia/Tokyo
